site_name: zerita
docs_dir: "../../docs/en"
site_dir: "../../site/en"

repo_name: zerita-lang/zerita
repo_url: https://github.com/zerita-lang/zerita/

nav:
  - Home: index.md
  - Dictionary: https://zerita-lang.github.io/dictionary/en/
  - Orthography: orthography.md
  - Articles: articles.md
  - Nouns: nouns.md

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.snippets

theme:
  name: material
  language: en

  icon:
    repo: fontawesome/brands/github

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - content.code.annotate
    - content.code.copy
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - search
    - search.suggest
    - search.share

plugins:
  - search:
      lang: en

extra:
  alternate:
    - name: 🇬🇧 English
      link: /zerita/
      lang: en
