site_name: zerita
docs_dir: "../../docs/en"
site_dir: "../../site/en"

repo_name: zerita-lang/zerita
repo_url: https://github.com/zerita-lang/zerita/

nav:
  - Home: index.md
  - Zerita overview:
      - overview/index.md
      - Dictionary: https://zerita-lang.github.io/dictionary/en/
      - Syntax:
          - overview/syntax/index.md
          # - Phrases: overview/syntax/phrases.md
          # - Words and lexemes: overview/syntax/words.md
      - Orthography: overview/orthography.md
  - Determinatives:
      - determinatives/index.md
      - Articles: determinatives/articles.md
      # - Demonstratives: determinatives/demonstratives.md
      # - Possessives: determinatives/possessives.md
      # - Quantifiers: determinatives/quantifiers.md
      - Numerals: determinatives/numerals.md
  - Nouns:
      - nouns/index.md
      - Gender: nouns/gender.md
      - Class: nouns/class.md
      - Number: nouns/number.md
      - Cases: nouns/cases.md
      - Pronouns:
          - nouns/pronouns/index.md
          - Personal pronouns: nouns/pronouns/personal.md
      - Declension tables: nouns/declension.md
  - Verbs:
      - verbs/index.md
      - Type: verbs/type.md
      - Person and number: verbs/person.md
      - Tense: verbs/tense.md
      - Mood: verbs/mood.md
      - Declension tables: verbs/declension.md
  - Description:
      # - description/index.md
      - Adjectives:
          - description/adjectives/index.md
          # - Grade: description/adjectives/grade.md
      - Adverbs:
          - description/adverbs/index.md
          - Derived adverbs: description/adverbs/derived.md
  - Connections:
      # - connection/index.md
      # - Coordination: connection/coordination.md
      # - Subordination: connection/subordination.md
      # - Relative clauses: connection/relative.md
      - Prepositions: connection/prepositions.md
      # - Particles: connection/particles.md
  - Conditionals:
      - conditionals/index.md
      - Antecedent: conditionals/antecedent.md
      - Consequent: conditionals/consequent.md
  - Questions:
      # - questions/index.md
      - Interrogatives: questions/interrogatives.md
      # - Interjection: questions/interjection.md
      - Negation: questions/negation.md

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.snippets

theme:
  name: material
  language: en

  icon:
    repo: fontawesome/brands/github

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - content.code.annotate
    - content.code.copy
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.top
    - navigation.tracking
    - search
    - search.suggest
    - search.share

plugins:
  - search:
      lang: en

extra:
  alternate:
    - name: 🇬🇧 English
      link: /zerita/en/
      lang: en
    - name: 🇬🇷 Ελληνικά
      link: /zerita/el/
      lang: el
