site_name: Ζερίτα
docs_dir: "../../docs/el"
site_dir: "../../site/el"

repo_name: zerita-lang/zerita
repo_url: https://github.com/zerita-lang/zerita/

nav:
  - Αρχική: index.md

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.snippets

theme:
  name: material
  language: el

  icon:
    repo: fontawesome/brands/github

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Αλλαγή σε σκοτεινή λειτουργία

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Αλλαγή σε φωτεινή λειτουργία

  features:
    - content.code.annotate
    - content.code.copy
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - search
    - search.suggest
    - search.share

plugins:
  - search:
      lang: el

extra:
  alternate:
    - name: 🇬🇧 English
      link: /zerita/en/
      lang: en
    - name: 🇬🇷 Ελληνικά
      link: /zerita/el/
      lang: el
